apiVersion: v1
kind: Service

metadata:
  name: argo-demo-canary
  namespace: demo

spec:
  type: ClusterIP

  selector:
    app: argo-demo

  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP