apiVersion: v1
kind: Service

metadata:
  name: argo-demo-stable
  namespace: demo

spec:
  type: LoadBalancer

  selector:
    app: argo-demo

  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP